bunkerchat/bunker

README.md

corrected startup command in readme

---

assets/app/messages/bunkerMessage.js

got twitter integration working

---

api/controllers/MessageController.js
api/services/RoomService.js
api/services/helpService.js
assets/app/header/HeaderController.js
assets/app/help/help.html
assets/app/room/rooms.js

fixed bug with help messages being broadcast to room

---

README.md
assets/app/room/fill.js
assets/styles/default.css
package.json

DB:  Fixing mobile scrolling.

---

api/controllers/MessageController.js

Magic8Ball

---

views/index.ejs

Saw some random vendor files without minified versions, especially the socket.io.js file.  This reduces the payload by 32kb, but adds another file. 
Thoughts?
-Josh

creating minified vendor bundle for non-minified vendor files

---

api/models/HangmanUserStatistics.js
api/services/hangmanService.js
api/services/statsForSelfTemplate.ejs
api/services/statsForUserTemplate.ejs
api/services/statsService.js

Adding hangman statistics

---

api/models/HangmanGame.js
api/models/HangmanPublicGameStatistics.js
api/services/hangmanService.js
api/services/help/hangman.txt
api/services/messageService.js

Private hangman and statistics for public games

Private hangman and statistics for public games

---

api/services/help/hangman.txt
api/services/statsForSelfTemplate.ejs
api/services/statsForUserTemplate.ejs
api/services/statsService.js

Better display of hangman stats and fix for hangman help

Better display of hangman stats and fix for hangman help

---

api/services/fightService.js
api/services/help/fight.txt

Changes to fight command to remove parameters and use a regex to remove extra noise

Changes to fight command to remove parameters and use a regex to remove extra noise

---

assets/app/header/header.html
assets/app/messages/bunkerMessage.js
assets/styles/default.css

Fixed the splash screen.
Updated the fatality gif.

i dono whats going on with my git hub, but the actual change is pretty small

---

api/services/help/basic.txt
api/services/help/leaderboard.txt
api/services/leaderboardService.js
api/services/leaderboardTemplate.ejs
api/services/loserboardTemplate.ejs
api/services/messageService.js

Adding leaderboard and loserboard for bunker games

Adding leaderboard and loserboard for bunker games

---

api/services/leaderboardService.js
api/services/leaderboardTemplate.ejs
api/services/loserboardTemplate.ejs

Making fight have winning percentage and overall W-L-T on leader/loser boards

Making fight have winning percentage and overall W-L-T on leader/loser boards

---

api/services/leaderboardService.js
api/services/leaderboardTemplate.ejs
api/services/loserboardTemplate.ejs

Expanding fight win percentage to top 10, adding half point for a tie for win percentage calculation change

Expanding fight win percentage to top 10, adding half point for a tie for win percentage calculation change

---

api/services/leaderboardService.js
api/services/leaderboardTemplate.ejs
api/services/loserboardTemplate.ejs
api/services/statsForSelfTemplate.ejs
api/services/statsForUserTemplate.ejs
api/services/statsService.js

Minimum 10 fights to include on leaderboard, added user stats for fight, fixed various issues with user stats

Minimum 10 fights to include on leaderboard, added user stats for fight, fixed various issues with user stats

---

api/services/fightService.js
api/services/help/fight.txt
api/services/messageService.js

Added list option to fight to show any pending fights you are a part of as either challenger or opponent.

Added list option to fight to show any pending fights you are a part of as either challenger or opponent.

---

bower.json
server/models/Poll.js
server/models/PollOption.js
server/services/help/poll.txt
server/services/help/vote.txt
server/services/messageService.js
server/services/pollService.js

Let me know if I'm missing something and I'll add it.

Basic Polls v1

---

assets/app/messages/bunkerMessage.js
assets/app/messages/messageLogScroll.js

image loading fix

---

src/components/message/MessageText.jsx
src/constants/theme.js
src/reducers/user.js

Light themes will use the v1 highlight color. Dark themes will either use the theme warning or info color with a white foreground color.

highlighting mentions

---

src/features/chat/Chat.jsx
src/features/header/Header.jsx
src/features/message/ScrollingMessageList.jsx
src/features/room/Room.jsx

fixed scrolling on mobile
